# Generated by Django 6.0.7 on 2026-09-17 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_date_of_birth"),
    ]

    operations = [
        migrations.CreateModel(
            name="VeriffVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("session_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("APPROVED", "Approved"),
                            ("DECLINED", "Declined"),
                            ("RESUBMISSION_REQUESTED", "Resubmission Requested"),
                            ("EXPIRED", "Expired"),
                            ("ABANDONED", "Abandoned"),
                        ],
                        default="IN_PROGRESS",
                        max_length=30,
                    ),
                ),
                (
                    "code",
                    models.IntegerField(
                        blank=True,
                        help_text="Veriff decision status code (e.g. 9001)",
                        null=True,
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "reason_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "vendor_data",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="veriff_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
