# Generated by Django 6.0.7 on 2026-09-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_veriffverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="block_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="custom_permissions",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("super_admin", "Super Admin"),
                    ("operations_admin", "Operations Admin"),
                    ("verification_admin", "Verification Admin"),
                    ("support_admin", "Support Admin"),
                    ("content_admin", "Content Admin"),
                    ("finance_admin", "Finance Admin"),
                ],
                default="user",
                max_length=30,
            ),
        ),
        migrations.DeleteModel(
            name="VeriffVerification",
        ),
    ]
