# Generated by Django 6.0.7 on 2026-09-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_block_reason_user_custom_permissions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="document_status",
            field=models.CharField(
                choices=[
                    ("NOT_UPLOADED", "Not Uploaded"),
                    ("PENDING", "Pending Verification"),
                    ("VERIFIED", "Verified"),
                    ("REJECTED", "Rejected"),
                ],
                default="NOT_UPLOADED",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="govt_id_back",
            field=models.ImageField(blank=True, null=True, upload_to="user_documents/"),
        ),
        migrations.AddField(
            model_name="user",
            name="govt_id_front",
            field=models.ImageField(blank=True, null=True, upload_to="user_documents/"),
        ),
        migrations.AddField(
            model_name="user",
            name="govt_id_number",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="govt_id_type",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
    ]
