# Generated by Django 6.0.7 on 2026-09-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_email_verified_user_email_verified_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="travel_preferences",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
