# Generated by Django 6.0.7 on 2026-09-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="actual_gps_track",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Historical driver GPS points [{lat, lng, timestamp}, ...]",
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ride",
            name="current_driver_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ride",
            name="current_driver_lng",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ride",
            name="drop_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="ride",
            name="drop_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ride",
            name="drop_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ride",
            name="estimated_distance_km",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ride",
            name="estimated_duration_mins",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ride",
            name="last_location_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ride",
            name="pickup_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="ride",
            name="pickup_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ride",
            name="pickup_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ride",
            name="route_geometry",
            field=models.JSONField(
                blank=True,
                help_text="GeoJSON coordinates array [[lng, lat], ...]",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ride",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
