# Generated by Django 6.0.7 on 2026-09-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0002_ride_actual_gps_track_ride_completed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="drop_place_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="ride",
            name="pickup_place_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
