# Generated by Django 6.0.7 on 2026-09-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0004_vehicle"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="features",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
