# Generated by Django 6.0.7 on 2026-09-24 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0006_rename_departure_time_and_add_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnRideReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("TRIGGERED", "Triggered"),
                            ("OPENED", "Opened"),
                            ("CREATED", "Created"),
                            ("SKIPPED", "Skipped"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("triggered_at", models.DateTimeField(blank=True, null=True)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="ride",
            name="is_return_ride",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="ride",
            name="original_ride",
            field=models.ForeignKey(
                blank=True,
                help_text="The original ride if this is a return ride",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="return_rides",
                to="rides.ride",
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="return_ride_status",
            field=models.CharField(
                choices=[
                    ("NOT_REQUESTED", "Not Requested"),
                    ("SCHEDULED_FOR_LATER", "Scheduled for Later"),
                    ("PENDING_CREATION", "Pending Creation"),
                    ("CREATED", "Created"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("SKIPPED", "Skipped"),
                ],
                db_index=True,
                default="NOT_REQUESTED",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="ride",
            index=models.Index(
                fields=["original_ride", "is_return_ride"], name="ride_return_rel_idx"
            ),
        ),
        migrations.AddField(
            model_name="returnridereminder",
            name="original_ride",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminders",
                to="rides.ride",
            ),
        ),
        migrations.AddField(
            model_name="returnridereminder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="return_ride_reminders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="returnridereminder",
            index=models.Index(
                fields=["user", "status"], name="ret_remind_user_stat_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="returnridereminder",
            index=models.Index(
                fields=["original_ride", "status"], name="ret_remind_ride_stat_idx"
            ),
        ),
    ]
