# Generated by Django 5.2.17 on 2026-09-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="cancellation_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="cancellation_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
