# Generated by Django 6.0.7 on 2026-09-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                ("category", models.CharField(default="other", max_length=50)),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("is_email_valid", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New Inquiry"),
                            ("RESPONDED", "Responded"),
                            ("INVALID_EMAIL", "Invalid Email"),
                            ("CLOSED", "Closed"),
                        ],
                        default="NEW",
                        max_length=30,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True, default="")),
                ("admin_replied_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
