# Generated by Django 6.0.7 on 2026-09-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_contactinquiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactinquiry",
            name="reply_history",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
