# Generated by Django 6.0.7 on 2026-09-18 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.SlugField(max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TRANSACTIONAL", "Transactional"),
                            ("MARKETING", "Marketing"),
                        ],
                        default="TRANSACTIONAL",
                        max_length=20,
                    ),
                ),
                ("subject_template", models.CharField(max_length=255)),
                ("body_html_template", models.TextField()),
                ("body_text_template", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmailAutomationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "event_trigger",
                    models.CharField(
                        choices=[
                            ("inactivity_7d", "Inactive for 7 days"),
                            ("inactivity_21d", "Inactive for 21 days"),
                            ("inactivity_30d", "Inactive for 30+ days"),
                            ("welcome_followup", "Welcome Follow-up"),
                        ],
                        max_length=50,
                    ),
                ),
                ("days_inactive", models.IntegerField(default=7)),
                ("require_email_verified", models.BooleanField(default=True)),
                ("require_marketing_consent", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_rules",
                        to="notifications.emailtemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("notification_type", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TRANSACTIONAL", "Transactional Email"),
                            ("MARKETING", "Marketing / Re-engagement Email"),
                        ],
                        default="TRANSACTIONAL",
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                (
                    "provider_name",
                    models.CharField(default="DjangoSMTP", max_length=50),
                ),
                (
                    "provider_message_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                            ("BOUNCED", "Bounced"),
                            ("OPENED", "Opened"),
                            ("CLICKED", "Clicked"),
                        ],
                        default="SENT",
                        max_length=20,
                    ),
                ),
                ("failure_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_account_security", models.BooleanField(default=True)),
                ("email_ride_updates", models.BooleanField(default=True)),
                ("email_messages", models.BooleanField(default=True)),
                ("email_platform_updates", models.BooleanField(default=True)),
                ("email_marketing", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
