# Generated by Django 6.0.7 on 2026-09-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0002_emailtemplate_emailautomationrule_notificationlog_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="link",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("booking_confirmed", "Booking Confirmed"),
                    ("booking_cancelled", "Booking Cancelled"),
                    ("ride_reminder", "Ride Reminder"),
                    ("return_ride_reminder", "Return Ride Reminder"),
                    ("new_message", "New Message"),
                    ("ride_update", "Ride Update"),
                    ("payment_update", "Payment Update"),
                    ("system", "System Notification"),
                ],
                default="system",
                max_length=50,
            ),
        ),
    ]
